Ministery of Education/Controllers/DashboardsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Ministery_of_Education.Models;

namespace AspnetCoreMvcFull.Controllers;

public class DashboardsController : Controller
{
  public IActionResult Index() => View();
}

Ministery of Education/Controllers/SchoolController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ministery_of_Education.Data;
using Ministery_of_Education.Models.Entities;
using Ministery_of_Education.Models.ViewModel;

namespace Ministery_of_Education.Controllers
{
    [Route("[controller]")]
    public class SchoolController : Controller
    {
        private readonly MinistryDbContext _ministryDbContext;

        public SchoolController(MinistryDbContext ministryDbContext)
        {
            _ministryDbContext = ministryDbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var schools = _ministryDbContext.Schools.ToList();
            var schooltype =  _ministryDbContext.SchoolTypes.ToList(); // Fetch the list of departments

            ViewData["SchoolType"] = schooltype;
            return View(schools);
        }

        [HttpPost]
        public async Task<IActionResult> AddSchool(SchoolViewModel schoolViewModel)
        {
            if (ModelState.IsValid)
            {
                var school = new School
                {
                    Name = schoolViewModel.Name,
                    Location = schoolViewModel.Location,
                    District = schoolViewModel.District,
                    Type = schoolViewModel.Type,
                    Email = schoolViewModel.Email
                };

                _ministryDbContext.Schools.Add(school);
                await _ministryDbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schoolViewModel);
        }

        [HttpPost]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var schoolToDelete = await _ministryDbContext.Schools.FindAsync(id);
            if (schoolToDelete != null)
            {
                _ministryDbContext.Schools.Remove(schoolToDelete);
                await _ministryDbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("Update/{id}")]
        public async Task<IActionResult> Update(int id, SchoolViewModel schoolViewModel)
        {
            var schoolToUpdate = await _ministryDbContext.Schools.FindAsync(id);
            if (schoolToUpdate != null)
            {
                schoolToUpdate.Name = schoolViewModel.Name;
                schoolToUpdate.Location = schoolViewModel.Location;
                schoolToUpdate.District = schoolViewModel.District;
                schoolToUpdate.Type = schoolViewModel.Type;
                schoolToUpdate.Email = schoolViewModel.Email;

                await _ministryDbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("EditSchool")]
        public async Task<IActionResult> EditSchool(SchoolViewModel schoolViewModel)
        {
            var schoolToUpdate = await _ministryDbContext.Schools.FindAsync(schoolViewModel.SchoolID);
            if (schoolToUpdate != null)
            {
                schoolToUpdate.Name = schoolViewModel.Name;
                schoolToUpdate.Location = schoolViewModel.Location;
                schoolToUpdate.District = schoolViewModel.District;
                schoolToUpdate.Type = schoolViewModel.Type;
                schoolToUpdate.Email = schoolViewModel.Email;

                await _ministryDbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Ministery of Education/Controllers/UserRoleController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ministery_of_Education.Data;
using Ministery_of_Education.Models.Entities;
using Ministery_of_Education.Models.ViewModel;

namespace Ministery_of_Education.Controllers
{
    [Route("[controller]")]
    public class UserRoleController : Controller
    {
        private readonly MinistryDbContext _ministryDbContext;

        public UserRoleController(MinistryDbContext ministryDbContext)
        {
            _ministryDbContext = ministryDbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userRoles = _ministryDbContext.UserRoles.ToList();
            return View(userRoles);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserRole(UserRoleViewModel roleUser)
        {
            if (ModelState.IsValid)
            {
                var userRoleData = new UserRole
                {
                    RoleName = roleUser.RoleName
                };

                _ministryDbContext.UserRoles.Add(userRoleData);
                await _ministryDbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(roleUser);
        }
        [HttpPost]
        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var userRoleToDelete = await _ministryDbContext.UserRoles.FindAsync(id);
            if (userRoleToDelete != null)
            {
                _ministryDbContext.UserRoles.Remove(userRoleToDelete);
                await _ministryDbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("Update/{id}")]
        public async Task<IActionResult> Update(int id, UserRole updatedUserRole)
        {
            var userRoleToUpdate = await _ministryDbContext.UserRoles.FindAsync(id);
            if (userRoleToUpdate != null)
            {
                // Update properties of userRoleToUpdate with values from updatedUserRole
                userRoleToUpdate.Id = updatedUserRole.Id; // Example property
                userRoleToUpdate.RoleName = updatedUserRole.RoleName; // Example property
                                                                      // Add more properties as needed

                await _ministryDbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("EditUserRole")]
        public async Task<IActionResult> EditUserRole(UserRole roleUser)
        {
            // (ModelState.IsValid)
            //
            _ministryDbContext.Entry(roleUser).State = EntityState.Modified;
            _ministryDbContext.SaveChanges();
            return RedirectToAction("Index");
            // Retrieve the existing record from the database
            //var existingUserRole = await _ministryDbContext.UserRoles.FindAsync(roleUser.Id);

            //if (existingUserRole == null)
            //{
            //    return NotFound(); // Handle case if role does not exist
            //}

            // Update the properties
            //existingUserRole.RoleName = roleUser.RoleName;

            // Save the changes
            //_ministryDbContext.UserRoles.Update(existingUserRole);
            //await _ministryDbContext.SaveChangesAsync();

            //return RedirectToAction(nameof(Index));
            //}

            return View(roleUser);
        }

    }
}

Ministery of Education/Views/Shared/Sections/Menu/_VerticalMenu.cshtml
@{
  TempData.Keep();
  string? currentPage = ViewContext.HttpContext.Request.Path;
}

<!-- Menu -->
@* ! Do this simple *@
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">

  @* ! Hide app brand if navbar-full *@
  <div
    class='app-brand demo @((@ViewData["navbarFull"] != null && Convert.ToBoolean(@ViewData["navbarFull"])) ? "d-xl-none" : "")'>
    <a asp-controller="Dashboards" asp-action="Index" class="app-brand-link">
      <span class="app-brand-logo demo">
        @await Html.PartialAsync("../_Partials/_Macros")
      </span>
      <span class="app-brand-text demo menu-text fw-bold ms-2">@TempData.Peek("appName")</span>
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm d-flex align-items-center justify-content-center"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  @* ! Full version menu-items *@
  <ul class="menu-inner py-1">
    <!-- Dashboards -->
    <li class='menu-item@(currentPage.EndsWith("/") || currentPage.StartsWith("/Dashboards/") ? " active open" : "")'>
      <a href="javascript:void(0);" class="menu-link ">
        <i class="menu-icon tf-icons bx bx-home-smile"></i>
        <div class="text-truncate" data-i18n="Dashboards">Dashboards</div>
        
      </a>

    </li>

    <!-- Layouts -->
    <li class='menu-item@(currentPage.StartsWith("/LayoutExamples") ? " active open" : "")'>
      <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icon bx bx-user-plus"></i>

        <div>Registration</div>
      </a>

      <ul class="menu-sub">

        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutMenu" ? " active" : "")'>
          <a asp-controller="School" asp-action="Index" class="menu-link">
            <div>School </div>
          </a>
        </li>

                <li class='menu-item@(currentPage == "/SchoolType/Index" ? " active" : "")'>
                    <a asp-controller="SchoolType" asp-action="Index" class="menu-link">
                        <div>School Type</div>
                    </a>
                </li>

        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutNavbar" ? " active" : "")'>
          <a asp-controller="LayoutExamples" asp-action="WithoutNavbar" class="menu-link">
            <div>Student</div>
          </a>
        </li>
        <li class='menu-item@(currentPage == "/LayoutExamples/Fluid" ? " active" : "")'>
          <a asp-controller="LayoutExamples" asp-action="Fluid" class="menu-link">
            <div>Teacher</div>
          </a>
        </li>
        <li class='menu-item@(currentPage == "/LayoutExamples/Container" ? " active" : "")'>
          <a asp-controller="LayoutExamples" asp-action="Container" class="menu-link">
            <div>Classes</div>
          </a>
        </li>
        <li class='menu-item@(currentPage == "/LayoutExamples/Blank" ? " active" : "")'>
          <a asp-controller="LayoutExamples" asp-action="Blank" class="menu-link">
            <div>Subject</div>
          </a>
        </li>
      </ul>
    </li>

    
  


    <!-- Report -->
    <li class='menu-item@(currentPage.StartsWith("/Pages/Account") ? " active open" : "")'>
      <a href="javascript:void(0);" class="menu-link menu-toggle">
        <i class="menu-icon tf-icons bx bx-dock-top"></i>
        <div>Reports</div>
      </a>
      <ul class="menu-sub">
        <li class='menu-item@(currentPage == "/Pages/AccountSettings" ? " active" : "")'>
          <a asp-controller="Pages" asp-action="AccountSettings" class="menu-link">
            <div>School</div>
          </a>
        </li>
        <li class='menu-item@(currentPage == "/Pages/AccountSettingsNotifications" ? " active" : "")'>
          <a asp-controller="Pages" asp-action="AccountSettingsNotifications" class="menu-link">
            <div>Students</div>
          </a>
        </li>
        <li class='menu-item@(currentPage == "/Pages/AccountSettingsConnections" ? " active" : "")'>
          <a asp-controller="Pages" asp-action="AccountSettingsConnections" class="menu-link">
            <div>Teacher</div>
          </a>
        </li>
      </ul>
    </li>
    <li class='menu-item@(currentPage.StartsWith("/Auth") ? " active open" : "")'>
      <a href="javascript:void(0);" class="menu-link menu-toggle">
    <i class="menu-icon tf-icons bx bx-cog"></i>
    <div>Settings</div>
</a>

      <ul class="menu-sub">
        <li class='menu-item@(currentPage == "/Auth/LoginBasic" ? " active" : "")'>
          <a asp-controller="User" asp-action="Index" class="menu-link" target="_blank">
         <div>Create User</div>
          </a>
        </li>

                <li class='menu-item@(currentPage == "/Auth/RegisterBasic" ? " active" : "")'>
                    <a asp-controller="UserRole" asp-action="Index" class="menu-link">
                        <div>User Role</div>
                    </a>
                </li>
        </li>
      </ul>
    </li>
  
      
   
  </ul>

</aside>
<!-- / Menu -->